apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikubegcp
spec:
  selector:
    matchLabels:
      app:  minikubegcp
  replicas: 2
  template:
    metadata:
      labels:
        app: minikubegcp
    spec:
      containers:
        - name: minikubegcp
          image: 08169752668/minikubegcp:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: minikubegcp
spec: 
  selector:
    app: minikubegcp
  ports: 
    - protocol: TCP
      port: 8080